# Generated by Django 4.1.6 on 2023-09-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatfield",
            name="userInput",
            field=models.CharField(max_length=1000),
        ),
    ]
